name: CustomJoinLeaveEvents
description: Custom join/leave events for your server.
main: Dapro718\CustomJoinLeaveEvents\Main
version: 0.0.2
api: 3.11.6
author: Dapro718
depend:
- FormAPI
permissions:
 message.disable:
  default: false
  description: Do not send a message when the player / group joins the server.
