name: CustomJoinLeave
description: Custom join/leave messages and events for your server.
main: Dapro718\CustomJoinLeave\Main
version: 0.0.1
api: 3.0.0
author: Dapro718
permissions:
 customjoinmessage.disable:
  default: false
  description: Do not send a custom message when a player / group joins the server.
 customleavemessage.disable:
  default: false
  description: Do not send a custom message when a player / group leaves the server.
